source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'ELKProgressView_Example' do
  pod 'ELKProgressView', :path => '../'
  pod 'ELKGCDTimer'
  target 'ELKProgressView_Tests' do
    inherit! :search_paths

    
  end
end
